#ifndef INC_GRAFICOS_H_
#define INC_GRAFICOS_H_

#include <stdint.h>

#define CELESTE_J1_FRAME_WIDTH 16U
#define CELESTE_J1_FRAME_HEIGHT 16U
#define CELESTE_J1_FRAME_COUNT 3U
#define CELESTE_J1_SHEET_WIDTH \
  (CELESTE_J1_FRAME_WIDTH * CELESTE_J1_FRAME_COUNT)
#define CELESTE_J1_JUMP_WIDTH 16U
#define CELESTE_J1_JUMP_HEIGHT 16U
#define CELESTE_J1_JUMP_WORD_COUNT \
  ((CELESTE_J1_JUMP_WIDTH * CELESTE_J1_JUMP_HEIGHT) / 2U)

extern const uint16_t CelesteJ1[
    CELESTE_J1_SHEET_WIDTH * CELESTE_J1_FRAME_HEIGHT];
extern const uint32_t CelesteJ1Jump[CELESTE_J1_JUMP_WORD_COUNT];

#endif /* INC_GRAFICOS_H_ */
