#ifndef LEVEL_BACKGROUND_H
#define LEVEL_BACKGROUND_H

#include <stdint.h>

#define LEVEL_BACKGROUND_WIDTH 240U
#define LEVEL_BACKGROUND_HEIGHT 320U
#define LEVEL_BACKGROUND_PIXEL_COUNT \
  (LEVEL_BACKGROUND_WIDTH * LEVEL_BACKGROUND_HEIGHT)
#define LEVEL_BACKGROUND_PACKED_WORD_COUNT \
  (LEVEL_BACKGROUND_PIXEL_COUNT / 2U)

extern const uint32_t level_background[LEVEL_BACKGROUND_PACKED_WORD_COUNT];

#endif /* LEVEL_BACKGROUND_H */
