#ifndef LEVEL_1_TEXTURE_H
#define LEVEL_1_TEXTURE_H

#include <stdint.h>

#define LEVEL_1_TEXTURE_WIDTH 240U
#define LEVEL_1_TEXTURE_HEIGHT 320U
#define LEVEL_1_TEXTURE_PIXEL_COUNT \
  (LEVEL_1_TEXTURE_WIDTH * LEVEL_1_TEXTURE_HEIGHT)
#define LEVEL_1_TEXTURE_PACKED_WORD_COUNT \
  (LEVEL_1_TEXTURE_PIXEL_COUNT / 2U)
#define LEVEL_1_TEXTURE_TRANSPARENT_COLOR 0x07E5U

extern const uint32_t level_1_texture[LEVEL_1_TEXTURE_PACKED_WORD_COUNT];

#endif /* LEVEL_1_TEXTURE_H */
