#ifndef START_BACKGROUND_H
#define START_BACKGROUND_H

#include <stdint.h>

#define START_BACKGROUND_WIDTH 240U
#define START_BACKGROUND_HEIGHT 320U
#define START_BACKGROUND_PIXEL_COUNT \
  (START_BACKGROUND_WIDTH * START_BACKGROUND_HEIGHT)

extern const uint16_t start_background[START_BACKGROUND_PIXEL_COUNT];

#endif /* START_BACKGROUND_H */
